QT += network

HEADERS += \
# Models
    $${PWD}/OAIAccountResponse.h \
    $${PWD}/OAIActionRowComponentForMessageRequest.h \
    $${PWD}/OAIActionRowComponentForMessageRequest_components_inner.h \
    $${PWD}/OAIActionRowComponentForModalRequest.h \
    $${PWD}/OAIActionRowComponentResponse.h \
    $${PWD}/OAIActionRowComponentResponse_components_inner.h \
    $${PWD}/OAIActivitiesAttachmentResponse.h \
    $${PWD}/OAIAdd_group_dm_user_201_response.h \
    $${PWD}/OAIAdd_group_dm_user_request.h \
    $${PWD}/OAIAdd_guild_member_request.h \
    $${PWD}/OAIAdd_lobby_member_request.h \
    $${PWD}/OAIApplicationCommandAttachmentOption.h \
    $${PWD}/OAIApplicationCommandAttachmentOptionResponse.h \
    $${PWD}/OAIApplicationCommandAutocompleteCallbackRequest.h \
    $${PWD}/OAIApplicationCommandAutocompleteCallbackRequest_data.h \
    $${PWD}/OAIApplicationCommandBooleanOption.h \
    $${PWD}/OAIApplicationCommandBooleanOptionResponse.h \
    $${PWD}/OAIApplicationCommandChannelOption.h \
    $${PWD}/OAIApplicationCommandChannelOptionResponse.h \
    $${PWD}/OAIApplicationCommandCreateRequest.h \
    $${PWD}/OAIApplicationCommandCreateRequest_options_inner.h \
    $${PWD}/OAIApplicationCommandIntegerOption.h \
    $${PWD}/OAIApplicationCommandIntegerOptionResponse.h \
    $${PWD}/OAIApplicationCommandInteractionMetadataResponse.h \
    $${PWD}/OAIApplicationCommandMentionableOption.h \
    $${PWD}/OAIApplicationCommandMentionableOptionResponse.h \
    $${PWD}/OAIApplicationCommandNumberOption.h \
    $${PWD}/OAIApplicationCommandNumberOptionResponse.h \
    $${PWD}/OAIApplicationCommandOptionIntegerChoice.h \
    $${PWD}/OAIApplicationCommandOptionIntegerChoiceResponse.h \
    $${PWD}/OAIApplicationCommandOptionNumberChoice.h \
    $${PWD}/OAIApplicationCommandOptionNumberChoiceResponse.h \
    $${PWD}/OAIApplicationCommandOptionStringChoice.h \
    $${PWD}/OAIApplicationCommandOptionStringChoiceResponse.h \
    $${PWD}/OAIApplicationCommandPatchRequestPartial.h \
    $${PWD}/OAIApplicationCommandPermission.h \
    $${PWD}/OAIApplicationCommandResponse.h \
    $${PWD}/OAIApplicationCommandResponse_options_inner.h \
    $${PWD}/OAIApplicationCommandRoleOption.h \
    $${PWD}/OAIApplicationCommandRoleOptionResponse.h \
    $${PWD}/OAIApplicationCommandStringOption.h \
    $${PWD}/OAIApplicationCommandStringOptionResponse.h \
    $${PWD}/OAIApplicationCommandSubcommandGroupOption.h \
    $${PWD}/OAIApplicationCommandSubcommandGroupOptionResponse.h \
    $${PWD}/OAIApplicationCommandSubcommandOption.h \
    $${PWD}/OAIApplicationCommandSubcommandOptionResponse.h \
    $${PWD}/OAIApplicationCommandSubcommandOptionResponse_options_inner.h \
    $${PWD}/OAIApplicationCommandSubcommandOption_options_inner.h \
    $${PWD}/OAIApplicationCommandUpdateRequest.h \
    $${PWD}/OAIApplicationCommandUserOption.h \
    $${PWD}/OAIApplicationCommandUserOptionResponse.h \
    $${PWD}/OAIApplicationFormPartial.h \
    $${PWD}/OAIApplicationFormPartial_description.h \
    $${PWD}/OAIApplicationFormPartial_integration_types_config_value.h \
    $${PWD}/OAIApplicationIncomingWebhookResponse.h \
    $${PWD}/OAIApplicationIntegrationTypeConfiguration.h \
    $${PWD}/OAIApplicationIntegrationTypeConfigurationResponse.h \
    $${PWD}/OAIApplicationOAuth2InstallParams.h \
    $${PWD}/OAIApplicationOAuth2InstallParamsResponse.h \
    $${PWD}/OAIApplicationResponse.h \
    $${PWD}/OAIApplicationRoleConnectionsMetadataItemRequest.h \
    $${PWD}/OAIApplicationRoleConnectionsMetadataItemResponse.h \
    $${PWD}/OAIApplicationUserRoleConnectionResponse.h \
    $${PWD}/OAIAttachmentResponse.h \
    $${PWD}/OAIAuditLogEntryResponse.h \
    $${PWD}/OAIAuditLogObjectChangeResponse.h \
    $${PWD}/OAIBan_user_from_guild_request.h \
    $${PWD}/OAIBaseCreateMessageCreateRequest.h \
    $${PWD}/OAIBaseCreateMessageCreateRequest_components_inner.h \
    $${PWD}/OAIBasicApplicationResponse.h \
    $${PWD}/OAIBasicMessageResponse.h \
    $${PWD}/OAIBasicMessageResponse_components_inner.h \
    $${PWD}/OAIBasicMessageResponse_interaction_metadata.h \
    $${PWD}/OAIBasicMessageResponse_nonce.h \
    $${PWD}/OAIBlockMessageAction.h \
    $${PWD}/OAIBlockMessageActionMetadata.h \
    $${PWD}/OAIBlockMessageActionMetadataResponse.h \
    $${PWD}/OAIBlockMessageActionResponse.h \
    $${PWD}/OAIBotAccountPatchRequest.h \
    $${PWD}/OAIBulkBanUsersResponse.h \
    $${PWD}/OAIBulkLobbyMemberRequest.h \
    $${PWD}/OAIBulk_ban_users_from_guild_request.h \
    $${PWD}/OAIBulk_delete_messages_request.h \
    $${PWD}/OAIBulk_update_guild_channels_request_inner.h \
    $${PWD}/OAIBulk_update_guild_roles_request_inner.h \
    $${PWD}/OAIButtonComponentForMessageRequest.h \
    $${PWD}/OAIButtonComponentResponse.h \
    $${PWD}/OAIChannelFollowerResponse.h \
    $${PWD}/OAIChannelFollowerWebhookResponse.h \
    $${PWD}/OAIChannelPermissionOverwriteRequest.h \
    $${PWD}/OAIChannelPermissionOverwriteResponse.h \
    $${PWD}/OAIChannelSelectComponentForMessageRequest.h \
    $${PWD}/OAIChannelSelectComponentResponse.h \
    $${PWD}/OAIChannelSelectDefaultValue.h \
    $${PWD}/OAIChannelSelectDefaultValueResponse.h \
    $${PWD}/OAICommandPermissionResponse.h \
    $${PWD}/OAICommandPermissionsResponse.h \
    $${PWD}/OAIComponentEmojiForMessageRequest.h \
    $${PWD}/OAIComponentEmojiResponse.h \
    $${PWD}/OAIConnectedAccountGuildResponse.h \
    $${PWD}/OAIConnectedAccountIntegrationResponse.h \
    $${PWD}/OAIConnectedAccountResponse.h \
    $${PWD}/OAIContainerComponentForMessageRequest.h \
    $${PWD}/OAIContainerComponentForMessageRequest_components_inner.h \
    $${PWD}/OAIContainerComponentResponse.h \
    $${PWD}/OAIContainerComponentResponse_components_inner.h \
    $${PWD}/OAICreateEntitlementRequestData.h \
    $${PWD}/OAICreateForumThreadRequest.h \
    $${PWD}/OAICreateGroupDMInviteRequest.h \
    $${PWD}/OAICreateGuildChannelRequest.h \
    $${PWD}/OAICreateGuildInviteRequest.h \
    $${PWD}/OAICreateGuildRequestChannelItem.h \
    $${PWD}/OAICreateGuildRequestRoleItem.h \
    $${PWD}/OAICreateMessageInteractionCallbackRequest.h \
    $${PWD}/OAICreateMessageInteractionCallbackResponse.h \
    $${PWD}/OAICreateOrUpdateThreadTagRequest.h \
    $${PWD}/OAICreatePrivateChannelRequest.h \
    $${PWD}/OAICreateTextThreadWithMessageRequest.h \
    $${PWD}/OAICreateTextThreadWithoutMessageRequest.h \
    $${PWD}/OAICreate_application_emoji_request.h \
    $${PWD}/OAICreate_auto_moderation_rule_200_response.h \
    $${PWD}/OAICreate_auto_moderation_rule_request.h \
    $${PWD}/OAICreate_channel_invite_request.h \
    $${PWD}/OAICreate_guild_emoji_request.h \
    $${PWD}/OAICreate_guild_from_template_request.h \
    $${PWD}/OAICreate_guild_role_request.h \
    $${PWD}/OAICreate_guild_scheduled_event_request.h \
    $${PWD}/OAICreate_guild_template_request.h \
    $${PWD}/OAICreate_interaction_response_request.h \
    $${PWD}/OAICreate_lobby_request.h \
    $${PWD}/OAICreate_or_join_lobby_request.h \
    $${PWD}/OAICreate_stage_instance_request.h \
    $${PWD}/OAICreate_thread_request.h \
    $${PWD}/OAICreate_webhook_request.h \
    $${PWD}/OAICreatedThreadResponse.h \
    $${PWD}/OAIDefaultKeywordListTriggerMetadata.h \
    $${PWD}/OAIDefaultKeywordListTriggerMetadataResponse.h \
    $${PWD}/OAIDefaultKeywordListUpsertRequest.h \
    $${PWD}/OAIDefaultKeywordListUpsertRequestPartial.h \
    $${PWD}/OAIDefaultKeywordListUpsertRequest_actions_inner.h \
    $${PWD}/OAIDefaultKeywordRuleResponse.h \
    $${PWD}/OAIDefaultKeywordRuleResponse_actions_inner.h \
    $${PWD}/OAIDefaultReactionEmojiResponse.h \
    $${PWD}/OAIDiscordIntegrationResponse.h \
    $${PWD}/OAIEdit_lobby_channel_link_request.h \
    $${PWD}/OAIEmbeddedActivityInstance.h \
    $${PWD}/OAIEmbeddedActivityInstance_location.h \
    $${PWD}/OAIEmojiResponse.h \
    $${PWD}/OAIEntitlementResponse.h \
    $${PWD}/OAIEntityMetadataExternal.h \
    $${PWD}/OAIEntityMetadataExternalResponse.h \
    $${PWD}/OAIError.h \
    $${PWD}/OAIErrorDetails.h \
    $${PWD}/OAIErrorResponse.h \
    $${PWD}/OAIExecute_webhook_request.h \
    $${PWD}/OAIExternalConnectionIntegrationResponse.h \
    $${PWD}/OAIExternalScheduledEventCreateRequest.h \
    $${PWD}/OAIExternalScheduledEventPatchRequestPartial.h \
    $${PWD}/OAIExternalScheduledEventResponse.h \
    $${PWD}/OAIFileComponentForMessageRequest.h \
    $${PWD}/OAIFileComponentResponse.h \
    $${PWD}/OAIFlagToChannelAction.h \
    $${PWD}/OAIFlagToChannelActionMetadata.h \
    $${PWD}/OAIFlagToChannelActionMetadataResponse.h \
    $${PWD}/OAIFlagToChannelActionResponse.h \
    $${PWD}/OAIFollow_channel_request.h \
    $${PWD}/OAIForumTagResponse.h \
    $${PWD}/OAIFriendInviteResponse.h \
    $${PWD}/OAIGatewayBotResponse.h \
    $${PWD}/OAIGatewayBotSessionStartLimitResponse.h \
    $${PWD}/OAIGatewayResponse.h \
    $${PWD}/OAIGet_channel_200_response.h \
    $${PWD}/OAIGet_entitlements_sku_ids_parameter.h \
    $${PWD}/OAIGet_sticker_200_response.h \
    $${PWD}/OAIGithubAuthor.h \
    $${PWD}/OAIGithubCheckApp.h \
    $${PWD}/OAIGithubCheckPullRequest.h \
    $${PWD}/OAIGithubCheckRun.h \
    $${PWD}/OAIGithubCheckRunOutput.h \
    $${PWD}/OAIGithubCheckSuite.h \
    $${PWD}/OAIGithubComment.h \
    $${PWD}/OAIGithubCommit.h \
    $${PWD}/OAIGithubDiscussion.h \
    $${PWD}/OAIGithubIssue.h \
    $${PWD}/OAIGithubRelease.h \
    $${PWD}/OAIGithubRepository.h \
    $${PWD}/OAIGithubReview.h \
    $${PWD}/OAIGithubUser.h \
    $${PWD}/OAIGithubWebhook.h \
    $${PWD}/OAIGroupDMInviteResponse.h \
    $${PWD}/OAIGuildAuditLogResponse.h \
    $${PWD}/OAIGuildAuditLogResponse_integrations_inner.h \
    $${PWD}/OAIGuildBanResponse.h \
    $${PWD}/OAIGuildChannelLocation.h \
    $${PWD}/OAIGuildChannelResponse.h \
    $${PWD}/OAIGuildCreateRequest.h \
    $${PWD}/OAIGuildHomeSettingsResponse.h \
    $${PWD}/OAIGuildIncomingWebhookResponse.h \
    $${PWD}/OAIGuildInviteResponse.h \
    $${PWD}/OAIGuildMFALevelResponse.h \
    $${PWD}/OAIGuildMemberResponse.h \
    $${PWD}/OAIGuildOnboardingResponse.h \
    $${PWD}/OAIGuildPatchRequestPartial.h \
    $${PWD}/OAIGuildPreviewResponse.h \
    $${PWD}/OAIGuildProductPurchaseResponse.h \
    $${PWD}/OAIGuildPruneResponse.h \
    $${PWD}/OAIGuildResponse.h \
    $${PWD}/OAIGuildRoleResponse.h \
    $${PWD}/OAIGuildRoleTagsResponse.h \
    $${PWD}/OAIGuildStickerResponse.h \
    $${PWD}/OAIGuildSubscriptionIntegrationResponse.h \
    $${PWD}/OAIGuildTemplateChannelResponse.h \
    $${PWD}/OAIGuildTemplateChannelTags.h \
    $${PWD}/OAIGuildTemplateResponse.h \
    $${PWD}/OAIGuildTemplateRoleResponse.h \
    $${PWD}/OAIGuildTemplateSnapshotResponse.h \
    $${PWD}/OAIGuildWelcomeChannel.h \
    $${PWD}/OAIGuildWelcomeScreenChannelResponse.h \
    $${PWD}/OAIGuildWelcomeScreenResponse.h \
    $${PWD}/OAIGuildWithCountsResponse.h \
    $${PWD}/OAIIncomingWebhookInteractionRequest.h \
    $${PWD}/OAIIncomingWebhookRequestPartial.h \
    $${PWD}/OAIIncomingWebhookUpdateForInteractionCallbackRequestPartial.h \
    $${PWD}/OAIIncomingWebhookUpdateRequestPartial.h \
    $${PWD}/OAIInnerErrors.h \
    $${PWD}/OAIIntegrationApplicationResponse.h \
    $${PWD}/OAIInteractionApplicationCommandAutocompleteCallbackIntegerData.h \
    $${PWD}/OAIInteractionApplicationCommandAutocompleteCallbackNumberData.h \
    $${PWD}/OAIInteractionApplicationCommandAutocompleteCallbackStringData.h \
    $${PWD}/OAIInteractionCallbackResponse.h \
    $${PWD}/OAIInteractionCallbackResponse_resource.h \
    $${PWD}/OAIInteractionResponse.h \
    $${PWD}/OAIInviteApplicationResponse.h \
    $${PWD}/OAIInviteChannelRecipientResponse.h \
    $${PWD}/OAIInviteChannelResponse.h \
    $${PWD}/OAIInviteGuildResponse.h \
    $${PWD}/OAIKeywordRuleResponse.h \
    $${PWD}/OAIKeywordTriggerMetadata.h \
    $${PWD}/OAIKeywordTriggerMetadataResponse.h \
    $${PWD}/OAIKeywordUpsertRequest.h \
    $${PWD}/OAIKeywordUpsertRequestPartial.h \
    $${PWD}/OAILaunchActivityInteractionCallbackRequest.h \
    $${PWD}/OAILaunchActivityInteractionCallbackResponse.h \
    $${PWD}/OAIListApplicationEmojisResponse.h \
    $${PWD}/OAIListGuildSoundboardSoundsResponse.h \
    $${PWD}/OAIList_auto_moderation_rules_200_response_inner.h \
    $${PWD}/OAIList_channel_invites_200_response_inner.h \
    $${PWD}/OAIList_channel_webhooks_200_response_inner.h \
    $${PWD}/OAIList_guild_integrations_200_response_inner.h \
    $${PWD}/OAIList_guild_scheduled_events_200_response_inner.h \
    $${PWD}/OAILobbyMemberRequest.h \
    $${PWD}/OAILobbyMemberResponse.h \
    $${PWD}/OAILobbyMessageResponse.h \
    $${PWD}/OAILobbyResponse.h \
    $${PWD}/OAIMLSpamRuleResponse.h \
    $${PWD}/OAIMLSpamUpsertRequest.h \
    $${PWD}/OAIMLSpamUpsertRequestPartial.h \
    $${PWD}/OAIMediaGalleryComponentForMessageRequest.h \
    $${PWD}/OAIMediaGalleryComponentResponse.h \
    $${PWD}/OAIMediaGalleryItemRequest.h \
    $${PWD}/OAIMediaGalleryItemResponse.h \
    $${PWD}/OAIMentionSpamRuleResponse.h \
    $${PWD}/OAIMentionSpamTriggerMetadata.h \
    $${PWD}/OAIMentionSpamTriggerMetadataResponse.h \
    $${PWD}/OAIMentionSpamUpsertRequest.h \
    $${PWD}/OAIMentionSpamUpsertRequestPartial.h \
    $${PWD}/OAIMentionableSelectComponentForMessageRequest.h \
    $${PWD}/OAIMentionableSelectComponentForMessageRequest_default_values_inner.h \
    $${PWD}/OAIMentionableSelectComponentResponse.h \
    $${PWD}/OAIMentionableSelectComponentResponse_default_values_inner.h \
    $${PWD}/OAIMessageAllowedMentionsRequest.h \
    $${PWD}/OAIMessageAttachmentRequest.h \
    $${PWD}/OAIMessageAttachmentResponse.h \
    $${PWD}/OAIMessageCallResponse.h \
    $${PWD}/OAIMessageComponentInteractionMetadataResponse.h \
    $${PWD}/OAIMessageCreateRequest.h \
    $${PWD}/OAIMessageEditRequestPartial.h \
    $${PWD}/OAIMessageEmbedAuthorResponse.h \
    $${PWD}/OAIMessageEmbedFieldResponse.h \
    $${PWD}/OAIMessageEmbedFooterResponse.h \
    $${PWD}/OAIMessageEmbedImageResponse.h \
    $${PWD}/OAIMessageEmbedProviderResponse.h \
    $${PWD}/OAIMessageEmbedResponse.h \
    $${PWD}/OAIMessageEmbedVideoResponse.h \
    $${PWD}/OAIMessageInteractionResponse.h \
    $${PWD}/OAIMessageMentionChannelResponse.h \
    $${PWD}/OAIMessageReactionCountDetailsResponse.h \
    $${PWD}/OAIMessageReactionEmojiResponse.h \
    $${PWD}/OAIMessageReactionResponse.h \
    $${PWD}/OAIMessageReferenceRequest.h \
    $${PWD}/OAIMessageReferenceResponse.h \
    $${PWD}/OAIMessageResponse.h \
    $${PWD}/OAIMessageRoleSubscriptionDataResponse.h \
    $${PWD}/OAIMessageSnapshotResponse.h \
    $${PWD}/OAIMessageStickerItemResponse.h \
    $${PWD}/OAIMinimalContentMessageResponse.h \
    $${PWD}/OAIModalInteractionCallbackRequest.h \
    $${PWD}/OAIModalInteractionCallbackRequestData.h \
    $${PWD}/OAIModalSubmitInteractionMetadataResponse.h \
    $${PWD}/OAIModalSubmitInteractionMetadataResponse_triggering_interaction_metadata.h \
    $${PWD}/OAIMyGuildResponse.h \
    $${PWD}/OAINewMemberActionResponse.h \
    $${PWD}/OAIOAuth2GetAuthorizationResponse.h \
    $${PWD}/OAIOAuth2GetKeys.h \
    $${PWD}/OAIOAuth2GetOpenIDConnectUserInfoResponse.h \
    $${PWD}/OAIOAuth2Key.h \
    $${PWD}/OAIOnboardingPromptOptionRequest.h \
    $${PWD}/OAIOnboardingPromptOptionResponse.h \
    $${PWD}/OAIOnboardingPromptResponse.h \
    $${PWD}/OAIPartialDiscordIntegrationResponse.h \
    $${PWD}/OAIPartialExternalConnectionIntegrationResponse.h \
    $${PWD}/OAIPartialGuildSubscriptionIntegrationResponse.h \
    $${PWD}/OAIPartner_sdk_unmerge_provisional_account_request.h \
    $${PWD}/OAIPinnedMessageResponse.h \
    $${PWD}/OAIPinnedMessagesResponse.h \
    $${PWD}/OAIPollAnswerCreateRequest.h \
    $${PWD}/OAIPollAnswerDetailsResponse.h \
    $${PWD}/OAIPollAnswerResponse.h \
    $${PWD}/OAIPollCreateRequest.h \
    $${PWD}/OAIPollEmoji.h \
    $${PWD}/OAIPollEmojiCreateRequest.h \
    $${PWD}/OAIPollMedia.h \
    $${PWD}/OAIPollMediaCreateRequest.h \
    $${PWD}/OAIPollMediaResponse.h \
    $${PWD}/OAIPollResponse.h \
    $${PWD}/OAIPollResultsEntryResponse.h \
    $${PWD}/OAIPollResultsResponse.h \
    $${PWD}/OAIPongInteractionCallbackRequest.h \
    $${PWD}/OAIPrivateApplicationResponse.h \
    $${PWD}/OAIPrivateChannelLocation.h \
    $${PWD}/OAIPrivateChannelResponse.h \
    $${PWD}/OAIPrivateGroupChannelResponse.h \
    $${PWD}/OAIPrivateGuildMemberResponse.h \
    $${PWD}/OAIProvisionalTokenResponse.h \
    $${PWD}/OAIPrune_guild_request.h \
    $${PWD}/OAIPrune_guild_request_include_roles.h \
    $${PWD}/OAIPurchaseNotificationResponse.h \
    $${PWD}/OAIQuarantineUserAction.h \
    $${PWD}/OAIQuarantineUserActionResponse.h \
    $${PWD}/OAIResolvedObjectsResponse.h \
    $${PWD}/OAIResourceChannelResponse.h \
    $${PWD}/OAIRichEmbed.h \
    $${PWD}/OAIRichEmbedAuthor.h \
    $${PWD}/OAIRichEmbedField.h \
    $${PWD}/OAIRichEmbedFooter.h \
    $${PWD}/OAIRichEmbedImage.h \
    $${PWD}/OAIRichEmbedProvider.h \
    $${PWD}/OAIRichEmbedThumbnail.h \
    $${PWD}/OAIRichEmbedVideo.h \
    $${PWD}/OAIRoleSelectComponentForMessageRequest.h \
    $${PWD}/OAIRoleSelectComponentResponse.h \
    $${PWD}/OAIRoleSelectDefaultValue.h \
    $${PWD}/OAIRoleSelectDefaultValueResponse.h \
    $${PWD}/OAISDKMessageRequest.h \
    $${PWD}/OAIScheduledEventResponse.h \
    $${PWD}/OAIScheduledEventUserResponse.h \
    $${PWD}/OAISectionComponentForMessageRequest.h \
    $${PWD}/OAISectionComponentForMessageRequest_accessory.h \
    $${PWD}/OAISectionComponentResponse.h \
    $${PWD}/OAISectionComponentResponse_accessory.h \
    $${PWD}/OAISeparatorComponentForMessageRequest.h \
    $${PWD}/OAISeparatorComponentResponse.h \
    $${PWD}/OAISet_channel_permission_overwrite_request.h \
    $${PWD}/OAISet_guild_application_command_permissions_request.h \
    $${PWD}/OAISet_guild_mfa_level_request.h \
    $${PWD}/OAISettingsEmojiResponse.h \
    $${PWD}/OAISlackWebhook.h \
    $${PWD}/OAISoundboardCreateRequest.h \
    $${PWD}/OAISoundboardPatchRequestPartial.h \
    $${PWD}/OAISoundboardSoundResponse.h \
    $${PWD}/OAISoundboardSoundSendRequest.h \
    $${PWD}/OAISpamLinkRuleResponse.h \
    $${PWD}/OAIStageInstanceResponse.h \
    $${PWD}/OAIStageScheduledEventCreateRequest.h \
    $${PWD}/OAIStageScheduledEventPatchRequestPartial.h \
    $${PWD}/OAIStageScheduledEventResponse.h \
    $${PWD}/OAIStandardStickerResponse.h \
    $${PWD}/OAIStickerPackCollectionResponse.h \
    $${PWD}/OAIStickerPackResponse.h \
    $${PWD}/OAIStringSelectComponentForMessageRequest.h \
    $${PWD}/OAIStringSelectComponentResponse.h \
    $${PWD}/OAIStringSelectOptionForMessageRequest.h \
    $${PWD}/OAIStringSelectOptionResponse.h \
    $${PWD}/OAITeamMemberResponse.h \
    $${PWD}/OAITeamResponse.h \
    $${PWD}/OAITextDisplayComponentForMessageRequest.h \
    $${PWD}/OAITextDisplayComponentResponse.h \
    $${PWD}/OAITextInputComponentForModalRequest.h \
    $${PWD}/OAITextInputComponentResponse.h \
    $${PWD}/OAIThreadMemberResponse.h \
    $${PWD}/OAIThreadMetadataResponse.h \
    $${PWD}/OAIThreadResponse.h \
    $${PWD}/OAIThreadSearchResponse.h \
    $${PWD}/OAIThread_search_tag_parameter.h \
    $${PWD}/OAIThreadsResponse.h \
    $${PWD}/OAIThumbnailComponentForMessageRequest.h \
    $${PWD}/OAIThumbnailComponentResponse.h \
    $${PWD}/OAIUnfurledMediaRequest.h \
    $${PWD}/OAIUnfurledMediaRequestWithAttachmentReferenceRequired.h \
    $${PWD}/OAIUnfurledMediaResponse.h \
    $${PWD}/OAIUpdateApplicationUserRoleConnectionRequest.h \
    $${PWD}/OAIUpdateDMRequestPartial.h \
    $${PWD}/OAIUpdateDefaultReactionEmojiRequest.h \
    $${PWD}/OAIUpdateGroupDMRequestPartial.h \
    $${PWD}/OAIUpdateGuildChannelRequestPartial.h \
    $${PWD}/OAIUpdateGuildOnboardingRequest.h \
    $${PWD}/OAIUpdateMessageInteractionCallbackRequest.h \
    $${PWD}/OAIUpdateMessageInteractionCallbackResponse.h \
    $${PWD}/OAIUpdateOnboardingPromptRequest.h \
    $${PWD}/OAIUpdateThreadRequestPartial.h \
    $${PWD}/OAIUpdateThreadTagRequest.h \
    $${PWD}/OAIUpdate_application_emoji_request.h \
    $${PWD}/OAIUpdate_auto_moderation_rule_request.h \
    $${PWD}/OAIUpdate_channel_request.h \
    $${PWD}/OAIUpdate_guild_emoji_request.h \
    $${PWD}/OAIUpdate_guild_member_request.h \
    $${PWD}/OAIUpdate_guild_scheduled_event_request.h \
    $${PWD}/OAIUpdate_guild_sticker_request.h \
    $${PWD}/OAIUpdate_guild_template_request.h \
    $${PWD}/OAIUpdate_guild_widget_settings_request.h \
    $${PWD}/OAIUpdate_my_guild_member_request.h \
    $${PWD}/OAIUpdate_self_voice_state_request.h \
    $${PWD}/OAIUpdate_stage_instance_request.h \
    $${PWD}/OAIUpdate_voice_state_request.h \
    $${PWD}/OAIUpdate_webhook_by_token_request.h \
    $${PWD}/OAIUpdate_webhook_request.h \
    $${PWD}/OAIUserAvatarDecorationResponse.h \
    $${PWD}/OAIUserCollectiblesResponse.h \
    $${PWD}/OAIUserCommunicationDisabledAction.h \
    $${PWD}/OAIUserCommunicationDisabledActionMetadata.h \
    $${PWD}/OAIUserCommunicationDisabledActionMetadataResponse.h \
    $${PWD}/OAIUserCommunicationDisabledActionResponse.h \
    $${PWD}/OAIUserGuildOnboardingResponse.h \
    $${PWD}/OAIUserNameplateResponse.h \
    $${PWD}/OAIUserPIIResponse.h \
    $${PWD}/OAIUserPrimaryGuildResponse.h \
    $${PWD}/OAIUserResponse.h \
    $${PWD}/OAIUserSelectComponentForMessageRequest.h \
    $${PWD}/OAIUserSelectComponentResponse.h \
    $${PWD}/OAIUserSelectDefaultValue.h \
    $${PWD}/OAIUserSelectDefaultValueResponse.h \
    $${PWD}/OAIVanityURLErrorResponse.h \
    $${PWD}/OAIVanityURLResponse.h \
    $${PWD}/OAIVoiceRegionResponse.h \
    $${PWD}/OAIVoiceScheduledEventCreateRequest.h \
    $${PWD}/OAIVoiceScheduledEventPatchRequestPartial.h \
    $${PWD}/OAIVoiceScheduledEventResponse.h \
    $${PWD}/OAIVoiceStateResponse.h \
    $${PWD}/OAIWebhookSlackEmbed.h \
    $${PWD}/OAIWebhookSlackEmbedField.h \
    $${PWD}/OAIWebhookSourceChannelResponse.h \
    $${PWD}/OAIWebhookSourceGuildResponse.h \
    $${PWD}/OAIWelcomeMessageResponse.h \
    $${PWD}/OAIWelcomeScreenPatchRequestPartial.h \
    $${PWD}/OAIWidgetActivity.h \
    $${PWD}/OAIWidgetChannel.h \
    $${PWD}/OAIWidgetMember.h \
    $${PWD}/OAIWidgetResponse.h \
    $${PWD}/OAIWidgetSettingsResponse.h \
# APIs
    $${PWD}/OAIDefaultApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIAccountResponse.cpp \
    $${PWD}/OAIActionRowComponentForMessageRequest.cpp \
    $${PWD}/OAIActionRowComponentForMessageRequest_components_inner.cpp \
    $${PWD}/OAIActionRowComponentForModalRequest.cpp \
    $${PWD}/OAIActionRowComponentResponse.cpp \
    $${PWD}/OAIActionRowComponentResponse_components_inner.cpp \
    $${PWD}/OAIActivitiesAttachmentResponse.cpp \
    $${PWD}/OAIAdd_group_dm_user_201_response.cpp \
    $${PWD}/OAIAdd_group_dm_user_request.cpp \
    $${PWD}/OAIAdd_guild_member_request.cpp \
    $${PWD}/OAIAdd_lobby_member_request.cpp \
    $${PWD}/OAIApplicationCommandAttachmentOption.cpp \
    $${PWD}/OAIApplicationCommandAttachmentOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandAutocompleteCallbackRequest.cpp \
    $${PWD}/OAIApplicationCommandAutocompleteCallbackRequest_data.cpp \
    $${PWD}/OAIApplicationCommandBooleanOption.cpp \
    $${PWD}/OAIApplicationCommandBooleanOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandChannelOption.cpp \
    $${PWD}/OAIApplicationCommandChannelOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandCreateRequest.cpp \
    $${PWD}/OAIApplicationCommandCreateRequest_options_inner.cpp \
    $${PWD}/OAIApplicationCommandIntegerOption.cpp \
    $${PWD}/OAIApplicationCommandIntegerOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandInteractionMetadataResponse.cpp \
    $${PWD}/OAIApplicationCommandMentionableOption.cpp \
    $${PWD}/OAIApplicationCommandMentionableOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandNumberOption.cpp \
    $${PWD}/OAIApplicationCommandNumberOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandOptionIntegerChoice.cpp \
    $${PWD}/OAIApplicationCommandOptionIntegerChoiceResponse.cpp \
    $${PWD}/OAIApplicationCommandOptionNumberChoice.cpp \
    $${PWD}/OAIApplicationCommandOptionNumberChoiceResponse.cpp \
    $${PWD}/OAIApplicationCommandOptionStringChoice.cpp \
    $${PWD}/OAIApplicationCommandOptionStringChoiceResponse.cpp \
    $${PWD}/OAIApplicationCommandPatchRequestPartial.cpp \
    $${PWD}/OAIApplicationCommandPermission.cpp \
    $${PWD}/OAIApplicationCommandResponse.cpp \
    $${PWD}/OAIApplicationCommandResponse_options_inner.cpp \
    $${PWD}/OAIApplicationCommandRoleOption.cpp \
    $${PWD}/OAIApplicationCommandRoleOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandStringOption.cpp \
    $${PWD}/OAIApplicationCommandStringOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandSubcommandGroupOption.cpp \
    $${PWD}/OAIApplicationCommandSubcommandGroupOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandSubcommandOption.cpp \
    $${PWD}/OAIApplicationCommandSubcommandOptionResponse.cpp \
    $${PWD}/OAIApplicationCommandSubcommandOptionResponse_options_inner.cpp \
    $${PWD}/OAIApplicationCommandSubcommandOption_options_inner.cpp \
    $${PWD}/OAIApplicationCommandUpdateRequest.cpp \
    $${PWD}/OAIApplicationCommandUserOption.cpp \
    $${PWD}/OAIApplicationCommandUserOptionResponse.cpp \
    $${PWD}/OAIApplicationFormPartial.cpp \
    $${PWD}/OAIApplicationFormPartial_description.cpp \
    $${PWD}/OAIApplicationFormPartial_integration_types_config_value.cpp \
    $${PWD}/OAIApplicationIncomingWebhookResponse.cpp \
    $${PWD}/OAIApplicationIntegrationTypeConfiguration.cpp \
    $${PWD}/OAIApplicationIntegrationTypeConfigurationResponse.cpp \
    $${PWD}/OAIApplicationOAuth2InstallParams.cpp \
    $${PWD}/OAIApplicationOAuth2InstallParamsResponse.cpp \
    $${PWD}/OAIApplicationResponse.cpp \
    $${PWD}/OAIApplicationRoleConnectionsMetadataItemRequest.cpp \
    $${PWD}/OAIApplicationRoleConnectionsMetadataItemResponse.cpp \
    $${PWD}/OAIApplicationUserRoleConnectionResponse.cpp \
    $${PWD}/OAIAttachmentResponse.cpp \
    $${PWD}/OAIAuditLogEntryResponse.cpp \
    $${PWD}/OAIAuditLogObjectChangeResponse.cpp \
    $${PWD}/OAIBan_user_from_guild_request.cpp \
    $${PWD}/OAIBaseCreateMessageCreateRequest.cpp \
    $${PWD}/OAIBaseCreateMessageCreateRequest_components_inner.cpp \
    $${PWD}/OAIBasicApplicationResponse.cpp \
    $${PWD}/OAIBasicMessageResponse.cpp \
    $${PWD}/OAIBasicMessageResponse_components_inner.cpp \
    $${PWD}/OAIBasicMessageResponse_interaction_metadata.cpp \
    $${PWD}/OAIBasicMessageResponse_nonce.cpp \
    $${PWD}/OAIBlockMessageAction.cpp \
    $${PWD}/OAIBlockMessageActionMetadata.cpp \
    $${PWD}/OAIBlockMessageActionMetadataResponse.cpp \
    $${PWD}/OAIBlockMessageActionResponse.cpp \
    $${PWD}/OAIBotAccountPatchRequest.cpp \
    $${PWD}/OAIBulkBanUsersResponse.cpp \
    $${PWD}/OAIBulkLobbyMemberRequest.cpp \
    $${PWD}/OAIBulk_ban_users_from_guild_request.cpp \
    $${PWD}/OAIBulk_delete_messages_request.cpp \
    $${PWD}/OAIBulk_update_guild_channels_request_inner.cpp \
    $${PWD}/OAIBulk_update_guild_roles_request_inner.cpp \
    $${PWD}/OAIButtonComponentForMessageRequest.cpp \
    $${PWD}/OAIButtonComponentResponse.cpp \
    $${PWD}/OAIChannelFollowerResponse.cpp \
    $${PWD}/OAIChannelFollowerWebhookResponse.cpp \
    $${PWD}/OAIChannelPermissionOverwriteRequest.cpp \
    $${PWD}/OAIChannelPermissionOverwriteResponse.cpp \
    $${PWD}/OAIChannelSelectComponentForMessageRequest.cpp \
    $${PWD}/OAIChannelSelectComponentResponse.cpp \
    $${PWD}/OAIChannelSelectDefaultValue.cpp \
    $${PWD}/OAIChannelSelectDefaultValueResponse.cpp \
    $${PWD}/OAICommandPermissionResponse.cpp \
    $${PWD}/OAICommandPermissionsResponse.cpp \
    $${PWD}/OAIComponentEmojiForMessageRequest.cpp \
    $${PWD}/OAIComponentEmojiResponse.cpp \
    $${PWD}/OAIConnectedAccountGuildResponse.cpp \
    $${PWD}/OAIConnectedAccountIntegrationResponse.cpp \
    $${PWD}/OAIConnectedAccountResponse.cpp \
    $${PWD}/OAIContainerComponentForMessageRequest.cpp \
    $${PWD}/OAIContainerComponentForMessageRequest_components_inner.cpp \
    $${PWD}/OAIContainerComponentResponse.cpp \
    $${PWD}/OAIContainerComponentResponse_components_inner.cpp \
    $${PWD}/OAICreateEntitlementRequestData.cpp \
    $${PWD}/OAICreateForumThreadRequest.cpp \
    $${PWD}/OAICreateGroupDMInviteRequest.cpp \
    $${PWD}/OAICreateGuildChannelRequest.cpp \
    $${PWD}/OAICreateGuildInviteRequest.cpp \
    $${PWD}/OAICreateGuildRequestChannelItem.cpp \
    $${PWD}/OAICreateGuildRequestRoleItem.cpp \
    $${PWD}/OAICreateMessageInteractionCallbackRequest.cpp \
    $${PWD}/OAICreateMessageInteractionCallbackResponse.cpp \
    $${PWD}/OAICreateOrUpdateThreadTagRequest.cpp \
    $${PWD}/OAICreatePrivateChannelRequest.cpp \
    $${PWD}/OAICreateTextThreadWithMessageRequest.cpp \
    $${PWD}/OAICreateTextThreadWithoutMessageRequest.cpp \
    $${PWD}/OAICreate_application_emoji_request.cpp \
    $${PWD}/OAICreate_auto_moderation_rule_200_response.cpp \
    $${PWD}/OAICreate_auto_moderation_rule_request.cpp \
    $${PWD}/OAICreate_channel_invite_request.cpp \
    $${PWD}/OAICreate_guild_emoji_request.cpp \
    $${PWD}/OAICreate_guild_from_template_request.cpp \
    $${PWD}/OAICreate_guild_role_request.cpp \
    $${PWD}/OAICreate_guild_scheduled_event_request.cpp \
    $${PWD}/OAICreate_guild_template_request.cpp \
    $${PWD}/OAICreate_interaction_response_request.cpp \
    $${PWD}/OAICreate_lobby_request.cpp \
    $${PWD}/OAICreate_or_join_lobby_request.cpp \
    $${PWD}/OAICreate_stage_instance_request.cpp \
    $${PWD}/OAICreate_thread_request.cpp \
    $${PWD}/OAICreate_webhook_request.cpp \
    $${PWD}/OAICreatedThreadResponse.cpp \
    $${PWD}/OAIDefaultKeywordListTriggerMetadata.cpp \
    $${PWD}/OAIDefaultKeywordListTriggerMetadataResponse.cpp \
    $${PWD}/OAIDefaultKeywordListUpsertRequest.cpp \
    $${PWD}/OAIDefaultKeywordListUpsertRequestPartial.cpp \
    $${PWD}/OAIDefaultKeywordListUpsertRequest_actions_inner.cpp \
    $${PWD}/OAIDefaultKeywordRuleResponse.cpp \
    $${PWD}/OAIDefaultKeywordRuleResponse_actions_inner.cpp \
    $${PWD}/OAIDefaultReactionEmojiResponse.cpp \
    $${PWD}/OAIDiscordIntegrationResponse.cpp \
    $${PWD}/OAIEdit_lobby_channel_link_request.cpp \
    $${PWD}/OAIEmbeddedActivityInstance.cpp \
    $${PWD}/OAIEmbeddedActivityInstance_location.cpp \
    $${PWD}/OAIEmojiResponse.cpp \
    $${PWD}/OAIEntitlementResponse.cpp \
    $${PWD}/OAIEntityMetadataExternal.cpp \
    $${PWD}/OAIEntityMetadataExternalResponse.cpp \
    $${PWD}/OAIError.cpp \
    $${PWD}/OAIErrorDetails.cpp \
    $${PWD}/OAIErrorResponse.cpp \
    $${PWD}/OAIExecute_webhook_request.cpp \
    $${PWD}/OAIExternalConnectionIntegrationResponse.cpp \
    $${PWD}/OAIExternalScheduledEventCreateRequest.cpp \
    $${PWD}/OAIExternalScheduledEventPatchRequestPartial.cpp \
    $${PWD}/OAIExternalScheduledEventResponse.cpp \
    $${PWD}/OAIFileComponentForMessageRequest.cpp \
    $${PWD}/OAIFileComponentResponse.cpp \
    $${PWD}/OAIFlagToChannelAction.cpp \
    $${PWD}/OAIFlagToChannelActionMetadata.cpp \
    $${PWD}/OAIFlagToChannelActionMetadataResponse.cpp \
    $${PWD}/OAIFlagToChannelActionResponse.cpp \
    $${PWD}/OAIFollow_channel_request.cpp \
    $${PWD}/OAIForumTagResponse.cpp \
    $${PWD}/OAIFriendInviteResponse.cpp \
    $${PWD}/OAIGatewayBotResponse.cpp \
    $${PWD}/OAIGatewayBotSessionStartLimitResponse.cpp \
    $${PWD}/OAIGatewayResponse.cpp \
    $${PWD}/OAIGet_channel_200_response.cpp \
    $${PWD}/OAIGet_entitlements_sku_ids_parameter.cpp \
    $${PWD}/OAIGet_sticker_200_response.cpp \
    $${PWD}/OAIGithubAuthor.cpp \
    $${PWD}/OAIGithubCheckApp.cpp \
    $${PWD}/OAIGithubCheckPullRequest.cpp \
    $${PWD}/OAIGithubCheckRun.cpp \
    $${PWD}/OAIGithubCheckRunOutput.cpp \
    $${PWD}/OAIGithubCheckSuite.cpp \
    $${PWD}/OAIGithubComment.cpp \
    $${PWD}/OAIGithubCommit.cpp \
    $${PWD}/OAIGithubDiscussion.cpp \
    $${PWD}/OAIGithubIssue.cpp \
    $${PWD}/OAIGithubRelease.cpp \
    $${PWD}/OAIGithubRepository.cpp \
    $${PWD}/OAIGithubReview.cpp \
    $${PWD}/OAIGithubUser.cpp \
    $${PWD}/OAIGithubWebhook.cpp \
    $${PWD}/OAIGroupDMInviteResponse.cpp \
    $${PWD}/OAIGuildAuditLogResponse.cpp \
    $${PWD}/OAIGuildAuditLogResponse_integrations_inner.cpp \
    $${PWD}/OAIGuildBanResponse.cpp \
    $${PWD}/OAIGuildChannelLocation.cpp \
    $${PWD}/OAIGuildChannelResponse.cpp \
    $${PWD}/OAIGuildCreateRequest.cpp \
    $${PWD}/OAIGuildHomeSettingsResponse.cpp \
    $${PWD}/OAIGuildIncomingWebhookResponse.cpp \
    $${PWD}/OAIGuildInviteResponse.cpp \
    $${PWD}/OAIGuildMFALevelResponse.cpp \
    $${PWD}/OAIGuildMemberResponse.cpp \
    $${PWD}/OAIGuildOnboardingResponse.cpp \
    $${PWD}/OAIGuildPatchRequestPartial.cpp \
    $${PWD}/OAIGuildPreviewResponse.cpp \
    $${PWD}/OAIGuildProductPurchaseResponse.cpp \
    $${PWD}/OAIGuildPruneResponse.cpp \
    $${PWD}/OAIGuildResponse.cpp \
    $${PWD}/OAIGuildRoleResponse.cpp \
    $${PWD}/OAIGuildRoleTagsResponse.cpp \
    $${PWD}/OAIGuildStickerResponse.cpp \
    $${PWD}/OAIGuildSubscriptionIntegrationResponse.cpp \
    $${PWD}/OAIGuildTemplateChannelResponse.cpp \
    $${PWD}/OAIGuildTemplateChannelTags.cpp \
    $${PWD}/OAIGuildTemplateResponse.cpp \
    $${PWD}/OAIGuildTemplateRoleResponse.cpp \
    $${PWD}/OAIGuildTemplateSnapshotResponse.cpp \
    $${PWD}/OAIGuildWelcomeChannel.cpp \
    $${PWD}/OAIGuildWelcomeScreenChannelResponse.cpp \
    $${PWD}/OAIGuildWelcomeScreenResponse.cpp \
    $${PWD}/OAIGuildWithCountsResponse.cpp \
    $${PWD}/OAIIncomingWebhookInteractionRequest.cpp \
    $${PWD}/OAIIncomingWebhookRequestPartial.cpp \
    $${PWD}/OAIIncomingWebhookUpdateForInteractionCallbackRequestPartial.cpp \
    $${PWD}/OAIIncomingWebhookUpdateRequestPartial.cpp \
    $${PWD}/OAIInnerErrors.cpp \
    $${PWD}/OAIIntegrationApplicationResponse.cpp \
    $${PWD}/OAIInteractionApplicationCommandAutocompleteCallbackIntegerData.cpp \
    $${PWD}/OAIInteractionApplicationCommandAutocompleteCallbackNumberData.cpp \
    $${PWD}/OAIInteractionApplicationCommandAutocompleteCallbackStringData.cpp \
    $${PWD}/OAIInteractionCallbackResponse.cpp \
    $${PWD}/OAIInteractionCallbackResponse_resource.cpp \
    $${PWD}/OAIInteractionResponse.cpp \
    $${PWD}/OAIInviteApplicationResponse.cpp \
    $${PWD}/OAIInviteChannelRecipientResponse.cpp \
    $${PWD}/OAIInviteChannelResponse.cpp \
    $${PWD}/OAIInviteGuildResponse.cpp \
    $${PWD}/OAIKeywordRuleResponse.cpp \
    $${PWD}/OAIKeywordTriggerMetadata.cpp \
    $${PWD}/OAIKeywordTriggerMetadataResponse.cpp \
    $${PWD}/OAIKeywordUpsertRequest.cpp \
    $${PWD}/OAIKeywordUpsertRequestPartial.cpp \
    $${PWD}/OAILaunchActivityInteractionCallbackRequest.cpp \
    $${PWD}/OAILaunchActivityInteractionCallbackResponse.cpp \
    $${PWD}/OAIListApplicationEmojisResponse.cpp \
    $${PWD}/OAIListGuildSoundboardSoundsResponse.cpp \
    $${PWD}/OAIList_auto_moderation_rules_200_response_inner.cpp \
    $${PWD}/OAIList_channel_invites_200_response_inner.cpp \
    $${PWD}/OAIList_channel_webhooks_200_response_inner.cpp \
    $${PWD}/OAIList_guild_integrations_200_response_inner.cpp \
    $${PWD}/OAIList_guild_scheduled_events_200_response_inner.cpp \
    $${PWD}/OAILobbyMemberRequest.cpp \
    $${PWD}/OAILobbyMemberResponse.cpp \
    $${PWD}/OAILobbyMessageResponse.cpp \
    $${PWD}/OAILobbyResponse.cpp \
    $${PWD}/OAIMLSpamRuleResponse.cpp \
    $${PWD}/OAIMLSpamUpsertRequest.cpp \
    $${PWD}/OAIMLSpamUpsertRequestPartial.cpp \
    $${PWD}/OAIMediaGalleryComponentForMessageRequest.cpp \
    $${PWD}/OAIMediaGalleryComponentResponse.cpp \
    $${PWD}/OAIMediaGalleryItemRequest.cpp \
    $${PWD}/OAIMediaGalleryItemResponse.cpp \
    $${PWD}/OAIMentionSpamRuleResponse.cpp \
    $${PWD}/OAIMentionSpamTriggerMetadata.cpp \
    $${PWD}/OAIMentionSpamTriggerMetadataResponse.cpp \
    $${PWD}/OAIMentionSpamUpsertRequest.cpp \
    $${PWD}/OAIMentionSpamUpsertRequestPartial.cpp \
    $${PWD}/OAIMentionableSelectComponentForMessageRequest.cpp \
    $${PWD}/OAIMentionableSelectComponentForMessageRequest_default_values_inner.cpp \
    $${PWD}/OAIMentionableSelectComponentResponse.cpp \
    $${PWD}/OAIMentionableSelectComponentResponse_default_values_inner.cpp \
    $${PWD}/OAIMessageAllowedMentionsRequest.cpp \
    $${PWD}/OAIMessageAttachmentRequest.cpp \
    $${PWD}/OAIMessageAttachmentResponse.cpp \
    $${PWD}/OAIMessageCallResponse.cpp \
    $${PWD}/OAIMessageComponentInteractionMetadataResponse.cpp \
    $${PWD}/OAIMessageCreateRequest.cpp \
    $${PWD}/OAIMessageEditRequestPartial.cpp \
    $${PWD}/OAIMessageEmbedAuthorResponse.cpp \
    $${PWD}/OAIMessageEmbedFieldResponse.cpp \
    $${PWD}/OAIMessageEmbedFooterResponse.cpp \
    $${PWD}/OAIMessageEmbedImageResponse.cpp \
    $${PWD}/OAIMessageEmbedProviderResponse.cpp \
    $${PWD}/OAIMessageEmbedResponse.cpp \
    $${PWD}/OAIMessageEmbedVideoResponse.cpp \
    $${PWD}/OAIMessageInteractionResponse.cpp \
    $${PWD}/OAIMessageMentionChannelResponse.cpp \
    $${PWD}/OAIMessageReactionCountDetailsResponse.cpp \
    $${PWD}/OAIMessageReactionEmojiResponse.cpp \
    $${PWD}/OAIMessageReactionResponse.cpp \
    $${PWD}/OAIMessageReferenceRequest.cpp \
    $${PWD}/OAIMessageReferenceResponse.cpp \
    $${PWD}/OAIMessageResponse.cpp \
    $${PWD}/OAIMessageRoleSubscriptionDataResponse.cpp \
    $${PWD}/OAIMessageSnapshotResponse.cpp \
    $${PWD}/OAIMessageStickerItemResponse.cpp \
    $${PWD}/OAIMinimalContentMessageResponse.cpp \
    $${PWD}/OAIModalInteractionCallbackRequest.cpp \
    $${PWD}/OAIModalInteractionCallbackRequestData.cpp \
    $${PWD}/OAIModalSubmitInteractionMetadataResponse.cpp \
    $${PWD}/OAIModalSubmitInteractionMetadataResponse_triggering_interaction_metadata.cpp \
    $${PWD}/OAIMyGuildResponse.cpp \
    $${PWD}/OAINewMemberActionResponse.cpp \
    $${PWD}/OAIOAuth2GetAuthorizationResponse.cpp \
    $${PWD}/OAIOAuth2GetKeys.cpp \
    $${PWD}/OAIOAuth2GetOpenIDConnectUserInfoResponse.cpp \
    $${PWD}/OAIOAuth2Key.cpp \
    $${PWD}/OAIOnboardingPromptOptionRequest.cpp \
    $${PWD}/OAIOnboardingPromptOptionResponse.cpp \
    $${PWD}/OAIOnboardingPromptResponse.cpp \
    $${PWD}/OAIPartialDiscordIntegrationResponse.cpp \
    $${PWD}/OAIPartialExternalConnectionIntegrationResponse.cpp \
    $${PWD}/OAIPartialGuildSubscriptionIntegrationResponse.cpp \
    $${PWD}/OAIPartner_sdk_unmerge_provisional_account_request.cpp \
    $${PWD}/OAIPinnedMessageResponse.cpp \
    $${PWD}/OAIPinnedMessagesResponse.cpp \
    $${PWD}/OAIPollAnswerCreateRequest.cpp \
    $${PWD}/OAIPollAnswerDetailsResponse.cpp \
    $${PWD}/OAIPollAnswerResponse.cpp \
    $${PWD}/OAIPollCreateRequest.cpp \
    $${PWD}/OAIPollEmoji.cpp \
    $${PWD}/OAIPollEmojiCreateRequest.cpp \
    $${PWD}/OAIPollMedia.cpp \
    $${PWD}/OAIPollMediaCreateRequest.cpp \
    $${PWD}/OAIPollMediaResponse.cpp \
    $${PWD}/OAIPollResponse.cpp \
    $${PWD}/OAIPollResultsEntryResponse.cpp \
    $${PWD}/OAIPollResultsResponse.cpp \
    $${PWD}/OAIPongInteractionCallbackRequest.cpp \
    $${PWD}/OAIPrivateApplicationResponse.cpp \
    $${PWD}/OAIPrivateChannelLocation.cpp \
    $${PWD}/OAIPrivateChannelResponse.cpp \
    $${PWD}/OAIPrivateGroupChannelResponse.cpp \
    $${PWD}/OAIPrivateGuildMemberResponse.cpp \
    $${PWD}/OAIProvisionalTokenResponse.cpp \
    $${PWD}/OAIPrune_guild_request.cpp \
    $${PWD}/OAIPrune_guild_request_include_roles.cpp \
    $${PWD}/OAIPurchaseNotificationResponse.cpp \
    $${PWD}/OAIQuarantineUserAction.cpp \
    $${PWD}/OAIQuarantineUserActionResponse.cpp \
    $${PWD}/OAIResolvedObjectsResponse.cpp \
    $${PWD}/OAIResourceChannelResponse.cpp \
    $${PWD}/OAIRichEmbed.cpp \
    $${PWD}/OAIRichEmbedAuthor.cpp \
    $${PWD}/OAIRichEmbedField.cpp \
    $${PWD}/OAIRichEmbedFooter.cpp \
    $${PWD}/OAIRichEmbedImage.cpp \
    $${PWD}/OAIRichEmbedProvider.cpp \
    $${PWD}/OAIRichEmbedThumbnail.cpp \
    $${PWD}/OAIRichEmbedVideo.cpp \
    $${PWD}/OAIRoleSelectComponentForMessageRequest.cpp \
    $${PWD}/OAIRoleSelectComponentResponse.cpp \
    $${PWD}/OAIRoleSelectDefaultValue.cpp \
    $${PWD}/OAIRoleSelectDefaultValueResponse.cpp \
    $${PWD}/OAISDKMessageRequest.cpp \
    $${PWD}/OAIScheduledEventResponse.cpp \
    $${PWD}/OAIScheduledEventUserResponse.cpp \
    $${PWD}/OAISectionComponentForMessageRequest.cpp \
    $${PWD}/OAISectionComponentForMessageRequest_accessory.cpp \
    $${PWD}/OAISectionComponentResponse.cpp \
    $${PWD}/OAISectionComponentResponse_accessory.cpp \
    $${PWD}/OAISeparatorComponentForMessageRequest.cpp \
    $${PWD}/OAISeparatorComponentResponse.cpp \
    $${PWD}/OAISet_channel_permission_overwrite_request.cpp \
    $${PWD}/OAISet_guild_application_command_permissions_request.cpp \
    $${PWD}/OAISet_guild_mfa_level_request.cpp \
    $${PWD}/OAISettingsEmojiResponse.cpp \
    $${PWD}/OAISlackWebhook.cpp \
    $${PWD}/OAISoundboardCreateRequest.cpp \
    $${PWD}/OAISoundboardPatchRequestPartial.cpp \
    $${PWD}/OAISoundboardSoundResponse.cpp \
    $${PWD}/OAISoundboardSoundSendRequest.cpp \
    $${PWD}/OAISpamLinkRuleResponse.cpp \
    $${PWD}/OAIStageInstanceResponse.cpp \
    $${PWD}/OAIStageScheduledEventCreateRequest.cpp \
    $${PWD}/OAIStageScheduledEventPatchRequestPartial.cpp \
    $${PWD}/OAIStageScheduledEventResponse.cpp \
    $${PWD}/OAIStandardStickerResponse.cpp \
    $${PWD}/OAIStickerPackCollectionResponse.cpp \
    $${PWD}/OAIStickerPackResponse.cpp \
    $${PWD}/OAIStringSelectComponentForMessageRequest.cpp \
    $${PWD}/OAIStringSelectComponentResponse.cpp \
    $${PWD}/OAIStringSelectOptionForMessageRequest.cpp \
    $${PWD}/OAIStringSelectOptionResponse.cpp \
    $${PWD}/OAITeamMemberResponse.cpp \
    $${PWD}/OAITeamResponse.cpp \
    $${PWD}/OAITextDisplayComponentForMessageRequest.cpp \
    $${PWD}/OAITextDisplayComponentResponse.cpp \
    $${PWD}/OAITextInputComponentForModalRequest.cpp \
    $${PWD}/OAITextInputComponentResponse.cpp \
    $${PWD}/OAIThreadMemberResponse.cpp \
    $${PWD}/OAIThreadMetadataResponse.cpp \
    $${PWD}/OAIThreadResponse.cpp \
    $${PWD}/OAIThreadSearchResponse.cpp \
    $${PWD}/OAIThread_search_tag_parameter.cpp \
    $${PWD}/OAIThreadsResponse.cpp \
    $${PWD}/OAIThumbnailComponentForMessageRequest.cpp \
    $${PWD}/OAIThumbnailComponentResponse.cpp \
    $${PWD}/OAIUnfurledMediaRequest.cpp \
    $${PWD}/OAIUnfurledMediaRequestWithAttachmentReferenceRequired.cpp \
    $${PWD}/OAIUnfurledMediaResponse.cpp \
    $${PWD}/OAIUpdateApplicationUserRoleConnectionRequest.cpp \
    $${PWD}/OAIUpdateDMRequestPartial.cpp \
    $${PWD}/OAIUpdateDefaultReactionEmojiRequest.cpp \
    $${PWD}/OAIUpdateGroupDMRequestPartial.cpp \
    $${PWD}/OAIUpdateGuildChannelRequestPartial.cpp \
    $${PWD}/OAIUpdateGuildOnboardingRequest.cpp \
    $${PWD}/OAIUpdateMessageInteractionCallbackRequest.cpp \
    $${PWD}/OAIUpdateMessageInteractionCallbackResponse.cpp \
    $${PWD}/OAIUpdateOnboardingPromptRequest.cpp \
    $${PWD}/OAIUpdateThreadRequestPartial.cpp \
    $${PWD}/OAIUpdateThreadTagRequest.cpp \
    $${PWD}/OAIUpdate_application_emoji_request.cpp \
    $${PWD}/OAIUpdate_auto_moderation_rule_request.cpp \
    $${PWD}/OAIUpdate_channel_request.cpp \
    $${PWD}/OAIUpdate_guild_emoji_request.cpp \
    $${PWD}/OAIUpdate_guild_member_request.cpp \
    $${PWD}/OAIUpdate_guild_scheduled_event_request.cpp \
    $${PWD}/OAIUpdate_guild_sticker_request.cpp \
    $${PWD}/OAIUpdate_guild_template_request.cpp \
    $${PWD}/OAIUpdate_guild_widget_settings_request.cpp \
    $${PWD}/OAIUpdate_my_guild_member_request.cpp \
    $${PWD}/OAIUpdate_self_voice_state_request.cpp \
    $${PWD}/OAIUpdate_stage_instance_request.cpp \
    $${PWD}/OAIUpdate_voice_state_request.cpp \
    $${PWD}/OAIUpdate_webhook_by_token_request.cpp \
    $${PWD}/OAIUpdate_webhook_request.cpp \
    $${PWD}/OAIUserAvatarDecorationResponse.cpp \
    $${PWD}/OAIUserCollectiblesResponse.cpp \
    $${PWD}/OAIUserCommunicationDisabledAction.cpp \
    $${PWD}/OAIUserCommunicationDisabledActionMetadata.cpp \
    $${PWD}/OAIUserCommunicationDisabledActionMetadataResponse.cpp \
    $${PWD}/OAIUserCommunicationDisabledActionResponse.cpp \
    $${PWD}/OAIUserGuildOnboardingResponse.cpp \
    $${PWD}/OAIUserNameplateResponse.cpp \
    $${PWD}/OAIUserPIIResponse.cpp \
    $${PWD}/OAIUserPrimaryGuildResponse.cpp \
    $${PWD}/OAIUserResponse.cpp \
    $${PWD}/OAIUserSelectComponentForMessageRequest.cpp \
    $${PWD}/OAIUserSelectComponentResponse.cpp \
    $${PWD}/OAIUserSelectDefaultValue.cpp \
    $${PWD}/OAIUserSelectDefaultValueResponse.cpp \
    $${PWD}/OAIVanityURLErrorResponse.cpp \
    $${PWD}/OAIVanityURLResponse.cpp \
    $${PWD}/OAIVoiceRegionResponse.cpp \
    $${PWD}/OAIVoiceScheduledEventCreateRequest.cpp \
    $${PWD}/OAIVoiceScheduledEventPatchRequestPartial.cpp \
    $${PWD}/OAIVoiceScheduledEventResponse.cpp \
    $${PWD}/OAIVoiceStateResponse.cpp \
    $${PWD}/OAIWebhookSlackEmbed.cpp \
    $${PWD}/OAIWebhookSlackEmbedField.cpp \
    $${PWD}/OAIWebhookSourceChannelResponse.cpp \
    $${PWD}/OAIWebhookSourceGuildResponse.cpp \
    $${PWD}/OAIWelcomeMessageResponse.cpp \
    $${PWD}/OAIWelcomeScreenPatchRequestPartial.cpp \
    $${PWD}/OAIWidgetActivity.cpp \
    $${PWD}/OAIWidgetChannel.cpp \
    $${PWD}/OAIWidgetMember.cpp \
    $${PWD}/OAIWidgetResponse.cpp \
    $${PWD}/OAIWidgetSettingsResponse.cpp \
# APIs
    $${PWD}/OAIDefaultApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
